### ISSUE TITLE
Always the same

### ISSUE THREAD

**Issue by trololol42** [phylopylo/Bombparty-Defuser#2]
I've noticied that when you play bombparty with this,
The extention will always give the same word, exemple "ANNEXATIONISMS" you can get this like 3 times in a raw, would it be possible to add a randomization in the word selection ?

**Comment by phylopylo** [comment]
Yes, I can add this feature when I get the chance. Currently, the extension is a minimum viable product, so there's definitely some improvements to be made.

**Comment by trololol42** [comment]
Yes surely, this project is recent after all, good luck with that and I'll be happy to see future improvement
